# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class GitTools < Formula
  desc "Git tools allow you to manage your git repository easily."
  homepage "https://github.com/kazhuravlev/git-tools"
  version "0.5.5"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kazhuravlev/git-tools/releases/download/v0.5.5/git-tools_0.5.5_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "995d09bd32e8eb268d965f278c1eb1ee302c97ae7652996d7eb5fda2531f41d2"

      def install
        bin.install "gt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazhuravlev/git-tools/releases/download/v0.5.5/git-tools_0.5.5_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "72fd4edd298a36685c54ccea6bd0979c6bfa770c0965c14ebd9146a88ecda9dd"

      def install
        bin.install "gt"
      end
    end
  end

  test do
    system "#{bin}/gt help"
  end
end
