# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitTools < Formula
  desc "Git tools allow you to manage your git repository easily."
  homepage "https://github.com/kazhuravlev/git-tools"
  version "0.5.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kazhuravlev/git-tools/releases/download/v0.5.7/git-tools_0.5.7_Darwin_arm64.tar.gz"
      sha256 "82132671b82193af806d6b2df2f721db5ce6d118d87e614efd9a379935b3f6b0"

      def install
        bin.install "gt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazhuravlev/git-tools/releases/download/v0.5.7/git-tools_0.5.7_Linux_arm64.tar.gz"
      sha256 "f0dadd5fed9502f3e8cbcc6986e4a2d80172c2ccc5ab2c0b7e18d01cbb1cd431"

      def install
        bin.install "gt"
      end
    end
  end

  test do
    system "#{bin}/gt help"
  end
end
